### ISSUE TITLE
Accept on PATCH and DELETE folders too

### ISSUE THREAD

**Issue by brumik** [brumik/ollama-obsidian-indexer#16]
https://github.com/brumik/obsidian-ollama-chat/issues/10

**Comment by brumik** [comment]
@tcarwash I think it has value to check in POST, PATCH and DELETE methods if it is a dir. 

1. Post is already doing dir and file too since it is used at startup.
2. The patch is called when a directory is renamed. This means it will be called with the directory.
3. Delete is tricky, I am not sure what is needed exactly to fix this (it won't fail but if we leave in a store old files, it will mess up a lot responses). It may be an easy fix too, but needs some investigation.

If you have time, feel free to give a stab at it, otherwise I will try to look into it later.

**Comment by tcarwash** [comment]
@brumik I'll try to take a look at the delete side, and the issue as a whole, a little closer this weekend. I'll let you know if I come up with anything

**Comment by brumik** [comment]
Any news here?

**Comment by tcarwash** [comment]
@brumik sorry about the delay, I had a crazy couple weeks. I have a [bugfix-16](https://github.com/tcarwash/ollama-obsidian-indexer/tree/bugfix-16) branch on my fork that I think solves this issue. 

I'm checking if the path is a folder, and if it is I call `index_dir` instead of `index_file`, and in `index_dir` I'm skipping any folders that don't have at least one `.md` file. 

I didn't do anything with the DELETE, it seemed to be working okay as it was

let me know if I'm on track there, or if you can think of anything that might break. I've done a little testing and it seems to be working correctly.

**Comment by brumik** [comment]
This issue was fixed in your PR, closing
