### ISSUE TITLE
FR: Integration with ollama-webui

### ISSUE THREAD

**Issue by vguillet** [brumik/ollama-obsidian-indexer#2]
Hey, just discovered your plugin for Obsidian, and I am loving it so far. 
This repo in particular has gotten me wondering whether it would eventually be possible to integrate the indexer with existing UIs frameworks such as [ollama-webui](https://github.com/ollama-webui/ollama-webui#troubleshooting). Being able to leverage my notes' content in those conversations would be absolutely fantastic, and would synergise very well with the modelfiles and prompts I have been putting together over time. 

I hope you eventually consider this for future updates! Cheers for the awesome work!

**Comment by brumik** [comment]
Hey, I do not see how this could be done, this project is not built to run on web, however if you have somethin that generates the web interface but runs and communicates locally much more is possible than this app is doing currently.

**Comment by brumik** [comment]
I am up to develop a plugin for the ollama web ui if you have ideas, but I myself is not using yet. I can see that with a plugin that scans and indexes your pc directories we could gain (even if not fine tuned but rather basic) helper to query any of your documents on your own PC. Feel free to contact me anywhere (or tag on gh). For now since this is out of scope of this project I am goint go close this issue :)
